id: https://ch.paf.link
name: ch-paf-link
prefixes:
  xsd: http://www.w3.org/2001/XMLSchema#
  linkml: https://w3id.org/linkml/
  chpaf: https://ch.paf.link/
  parl: https://politics.ld.admin.ch/parliamentary-affair/
imports:
  - linkml:types
default_prefix: chpaf
default_range: string
  
classes:
  
  ParliamentaryAffairIdentifierEntity:
    slots:
      - id
      - parliamentaryAffairIdentifier
    id_prefixes:
      - parl
  
  ProceduralRequestReportActivity:
    slots:
      - id
      - proceduralRequestReportYear
  
  ParliamentaryDataContainer:
    tree_root: true
    attributes:
      affair:
        multivalued: true
        inlined_as_list: true
        range: ParliamentaryAffairIdentifierEntity
      report:
        multivalued: true
        inlined_as_list: true
        range: ProceduralRequestReportActivity

slots:
  id:
    identifier: true
  parliamentaryAffairIdentifier:
    required: true
  proceduralRequestReportYear:
    required: true
    range: gYear

types:
  gYear:
    uri: xsd:gYear
    base: str
    pattern: "^[0-9]{4}$"